pub mod cell;
pub mod choice_control;
pub mod choice_point;
pub mod codegen;
mod codegen_terms;
pub mod compiler;
pub mod composite_provider;
pub mod embed_adapter;
pub mod embedding_queue;
pub mod embedding_worker;
pub mod environment;
pub mod environment_stack;
pub mod error;
pub mod execution_result;
pub mod executor;
mod executor_index;
pub mod executor_solve;
mod executor_terms;
pub mod fact_key;
pub mod fact_provider;
pub mod heap;
pub mod index_provider;
pub mod instruction;
pub mod machine;
pub mod permanent_vars;
pub mod persistent_embedding_queue;
pub mod predicate;
pub mod program;
pub mod program_codegen;
pub mod query_codegen;
pub mod register;
pub mod rule_codegen;
pub mod rule_store;
pub mod runtime;
pub mod storage_index_writer;
pub mod storage_provider;
pub mod storage_retract;
pub mod storage_writer;
pub mod structure_mode;
pub mod structure_ops;
pub mod term_reader;
pub mod trail;
pub mod unification;

pub use cell::Cell;
pub use choice_point::ChoicePointFrame;
pub use codegen::WamCodegen;
pub use compiler::M0Compiler;
pub use composite_provider::CompositeFactProvider;
pub use embed_adapter::BlockingEmbeddingProvider;
pub use embedding_queue::{EmbeddingJob, EmbeddingQueue};
pub use embedding_worker::EmbeddingWorker;
pub use error::{WamError, WamResult};
pub use execution_result::ExecutionResult;
pub use executor::WamExecutor;
pub use fact_key::{
    term_to_delete_pattern, term_to_fact_key, DeletePattern, FactKey, MutationEvent,
};
pub use fact_provider::{FactProvider, StaticFactProvider};
pub use heap::Heap;
pub use index_provider::IndexFactProvider;
pub use instruction::Instruction;
pub use machine::M0Machine;
pub use persistent_embedding_queue::{PersistentEmbeddingJob, PersistentEmbeddingQueue};
pub use predicate::{compound_args, predicate_key, PredicateKey};
pub use program::WamProgram;
pub use program_codegen::{compile_query_program, compile_query_program_with_bindings};
pub use query_codegen::CompiledQuery;
pub use register::RegisterFile;
pub use rule_store::{CompiledRuleArtifact, StorageRuleStore};
pub use runtime::WamRuntime;
pub use storage_index_writer::{Embedder, IndexedStorageFactWriter};
pub use storage_provider::StorageFactProvider;
pub use storage_writer::StorageFactWriter;
pub use trail::Trail;
pub use unification::Unifier;

#[cfg(test)]
mod tests;
