pub mod cell;
pub mod choice_control;
pub mod choice_point;
pub mod codegen;
pub mod compiler;
pub mod composite_provider;
pub mod embed_adapter;
pub mod embedding_queue;
pub mod embedding_worker;
pub mod environment;
pub mod environment_stack;
pub mod error;
pub mod execution_result;
pub mod executor;
pub mod executor_solve;
pub mod fact_provider;
pub mod heap;
pub mod index_provider;
pub mod instruction;
pub mod m1;
pub mod m2;
pub mod m3;
pub mod machine;
pub mod persistent_embedding_queue;
pub mod predicate;
pub mod program;
pub mod program_codegen;
pub mod query_codegen;
pub mod register;
pub mod rule_codegen;
pub mod rule_store;
pub mod runtime;
pub mod storage_index_writer;
pub mod storage_provider;
pub mod storage_writer;
pub mod structure_mode;
pub mod structure_ops;
pub mod term_reader;
pub mod trail;
pub mod unification;
pub mod variable_analysis;

pub use cell::Cell;
pub use choice_point::ChoicePointFrame;
pub use codegen::WamCodegen;
pub use compiler::M0Compiler;
pub use composite_provider::CompositeFactProvider;
pub use embed_adapter::BlockingEmbeddingProvider;
pub use embedding_queue::{EmbeddingJob, EmbeddingQueue};
pub use embedding_worker::EmbeddingWorker;
pub use environment::EnvironmentFrame;
pub use error::{WamError, WamResult};
pub use execution_result::ExecutionResult;
pub use executor::WamExecutor;
pub use fact_provider::{FactProvider, StaticFactProvider};
pub use heap::Heap;
pub use index_provider::IndexFactProvider;
pub use instruction::Instruction;
pub use m1::{compile_fact, CompiledFact, M1Machine};
pub use m2::{compile_facts, compile_rule, CompiledRule, M2Machine};
pub use m3::{Bindings, ChoicePoint, M3Machine, M3Program};
pub use machine::M0Machine;
pub use persistent_embedding_queue::{PersistentEmbeddingJob, PersistentEmbeddingQueue};
pub use predicate::{compound_args, predicate_key, PredicateKey};
pub use program::WamProgram;
pub use program_codegen::{compile_query_program, compile_query_program_with_bindings};
pub use query_codegen::CompiledQuery;
pub use register::RegisterFile;
pub use rule_store::{CompiledRuleArtifact, StorageRuleStore};
pub use runtime::WamRuntime;
pub use storage_index_writer::{Embedder, IndexedStorageFactWriter};
pub use storage_provider::StorageFactProvider;
pub use storage_writer::StorageFactWriter;
pub use trail::Trail;
pub use unification::Unifier;
pub use variable_analysis::{permanent_variables, variables_in};

#[cfg(test)]
mod tests;
